name: Protect
main: com.mengcraft.protect.Main
version: ${project.version}
author: meng

commands:
  protect:
    description: Operator command for this plug-in.
    permission: protect.admin

permissions:
  protect.admin:
    description: Operator permission for this plug-in.
    default: op

softdepend: [Yum]